// All 63 U.S. national parks, tiered.
// PETER: this is a draft ranking. Move parks between tiers until it's yours;
// the site renders whatever order these arrays are in.
export type Tier = { label: string; color: string; parks: string[] };

// What each tier means. Used to argue with visitors who move things.
export const TIER_DEFENSE: Record<string, string> = {
  S: "S-tier is for parks that rearrange something in you. Every park up there has done it. It is not a list of parks that are merely excellent.",
  A: "A-tier is the honor roll: world-class, zero notes, but it didn't change my life, and I keep the top shelf honest.",
  B: "B-tier means a great weekend, planned well. That is a compliment, not an insult.",
  C: "C-tier means I'm glad it's protected, I'm glad I saw it, and I would not reroute a road trip for it.",
  D: "D-tier parks are perfectly fine places that became national parks for reasons that are mostly political.",
};

// One load-bearing fact per park, used to build the rebuttal.
export const PARK_FACTS: Record<string, string> = {
  Yellowstone: "it was the first national park on Earth and sits on an active supervolcano",
  Yosemite: "its granite walls made Ansel Adams an entire career",
  Glacier: "the Going-to-the-Sun Road alone would justify the tier",
  Zion: "Angels Landing might be the best four hours of hiking in America",
  "Grand Canyon": "it is a mile-deep hole you can see from space",
  "Grand Teton": "it is the most photogenic mountain range in the lower 48",
  "Theodore Roosevelt": "it is named after the man himself",
  Olympic: "it fits a rainforest, alpine ridges, and Pacific coastline into one park",
  "Mount Rainier": "it is a 14,000-foot volcano looming over Seattle",
  "Rocky Mountain": "Trail Ridge Road tops out above 12,000 feet",
  "Bryce Canyon": "the hoodoo amphitheater genuinely looks computer-rendered",
  "Great Smoky Mountains": "it is the most visited park in the country for a reason",
  Denali: "it holds the tallest peak in North America",
  Sequoia: "some of those trees predate the Roman Empire",
  Arches: "there are more than two thousand natural stone arches in it",
  "Crater Lake": "it is the deepest, bluest lake in the United States",
  Acadia: "for half the year it is the first place sunrise touches the country",
  "Hawaiʻi Volcanoes": "the park is actively growing new land as we speak",
  "Kenai Fjords": "you can watch glaciers calve into the sea",
  Canyonlands: "the view from Island in the Sky is absurd",
  "Death Valley": "it is the hottest place on the planet",
  "Joshua Tree": "the boulder fields and Seussian trees are a real aesthetic",
  Redwood: "it protects the tallest living things on Earth",
  Shenandoah: "Skyline Drive runs 105 miles along the Blue Ridge",
  "North Cascades": "it has more glaciers than any US park outside Alaska",
  "Big Bend": "it has the darkest night skies in the lower 48",
  Badlands: "striped rock, roaming bison, very cinematic",
  "Capitol Reef": "it is a hundred-mile wrinkle in the earth's crust",
  "Kings Canyon": "the canyon is deeper than the Grand one",
  "Haleakalā": "sunrise above the clouds at 10,000 feet is real",
  Katmai: "the bears fishing at Brooks Falls are the best livestream on the internet",
  "Glacier Bay": "sixty-five miles of ice that was solid land in 1750",
  "Mesa Verde": "the cliff dwellings have stood for 700 years",
  "White Sands": "you can sled down gypsum dunes",
  "Great Sand Dunes": "750-foot dunes piled against the Sangre de Cristos is a wild sight",
  Everglades: "it is the only place on Earth where alligators and crocodiles coexist",
  "Mammoth Cave": "it is the longest cave system known to exist",
  "Carlsbad Caverns": "half a million bats exit the cave every evening like smoke",
  "Petrified Forest": "the logs are 225 million years old and made of stone",
  Saguaro: "the cacti have more personality than most people",
  "Lassen Volcanic": "it has every type of volcano that exists",
  "Channel Islands": "people call it the Galápagos of North America",
  Pinnacles: "there are condors circling the spires",
  "New River Gorge": "one of the oldest rivers in the world runs under the newest park",
  "Great Basin": "the bristlecone pines are pushing 5,000 years old",
  Voyageurs: "it is a park you traverse by boat",
  "Isle Royale": "wolves and moose run a predator-prey study on an island",
  "Wind Cave": "the boxwork formations barely exist anywhere else",
  "Guadalupe Mountains": "it contains the highest point in Texas",
  "Black Canyon of the Gunnison": "the walls are so steep sunlight barely reaches the river",
  "Wrangell–St. Elias": "it is the largest national park, six Yellowstones of land",
  "Lake Clark": "turquoise lakes, brown bears, and not a single road in",
  "Dry Tortugas": "there is a Civil War fort seventy miles out to sea",
  "Virgin Islands": "the reefs and beaches are legitimately gorgeous",
  Biscayne: "the park is 95 percent underwater",
  "Gateway Arch": "it is an arch, downtown, next to a highway",
  "Indiana Dunes": "it is a beach with a view of a steel mill",
  "Cuyahoga Valley": "it is a very nice towpath between Cleveland and Akron",
  "Hot Springs": "the springs are historic, and also piped indoors",
  Congaree: "the old-growth floodplain is real, and so are the mosquitoes",
  "Kobuk Valley": "arctic sand dunes with zero roads, trails, or visitors",
  "Gates of the Arctic": "there are no roads, no trails, and no entrance",
  "American Samoa": "it is gorgeous and also a 5,000-mile flight away",
};

export const PARK_TIERS: Tier[] = [
  {
    label: "S",
    color: "#ff7f7e",
    parks: [
      "Yellowstone",
      "Yosemite",
      "Glacier",
      "Black Canyon of the Gunnison",
      "Grand Canyon",
      "Grand Teton",
      "Theodore Roosevelt", // obviously
    ],
  },
  {
    label: "A",
    color: "#ffbf7f",
    parks: [
      "Olympic",
      "Mount Rainier",
      "Rocky Mountain",
      "Bryce Canyon",
      "Great Smoky Mountains",
      "Denali",
      "Sequoia",
      "Arches",
      "Crater Lake",
      "Acadia",
      "Hawaiʻi Volcanoes",
      "Kenai Fjords",
    ],
  },
  {
    label: "B",
    color: "#ffdf80",
    parks: [
      "Canyonlands",
      "Death Valley",
      "Joshua Tree",
      "Redwood",
      "Shenandoah",
      "North Cascades",
      "Big Bend",
      "Badlands",
      "Capitol Reef",
      "Kings Canyon",
      "Haleakalā",
      "Katmai",
      "Glacier Bay",
      "Mesa Verde",
      "White Sands",
      "Great Sand Dunes",
    ],
  },
  {
    label: "C",
    color: "#feff7f",
    parks: [
      "Everglades",
      "Mammoth Cave",
      "Carlsbad Caverns",
      "Petrified Forest",
      "Saguaro",
      "Lassen Volcanic",
      "Channel Islands",
      "Pinnacles",
      "New River Gorge",
      "Great Basin",
      "Voyageurs",
      "Isle Royale",
      "Wind Cave",
      "Guadalupe Mountains",
      "Zion",
      "Wrangell–St. Elias",
      "Lake Clark",
      "Dry Tortugas",
      "Virgin Islands",
      "Biscayne",
    ],
  },
  {
    label: "D",
    color: "#bfff7f",
    parks: [
      "Gateway Arch",
      "Indiana Dunes",
      "Cuyahoga Valley",
      "Hot Springs",
      "Congaree",
      "Kobuk Valley",
      "Gates of the Arctic",
      "American Samoa",
    ],
  },
];
